---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)8s - %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: automl.log

  distributed_logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: distributed.log


root:
  level: DEBUG
  handlers: [ console, file_handler ]

loggers:
  smac:
    level: INFO

  matplotlib:
    level: WARNING

  numba:
    level: WARNING

  TAE:
    level: INFO